// 本文件由 scripts/gen-deck.mjs 从「八男杀-104张基础配牌表.csv」生成，请勿手改。
// 每张实体牌保留唯一 cardId（编号），花色与点数成为结构化字段。

import type { CardInstance } from '@engine/types';

export const DECK_SIZE = 104;

export const BASE_DECK: CardInstance[] = [
  { id: "1-♠01", deck: 1, suit: "♠", rank: 1, name: "普通杀", type: "基本" },
  { id: "1-♠02", deck: 1, suit: "♠", rank: 2, name: "闪", type: "基本" },
  { id: "1-♠03", deck: 1, suit: "♠", rank: 3, name: "方天画戟", type: "武器" },
  { id: "1-♠04", deck: 1, suit: "♠", rank: 4, name: "雷杀", type: "基本" },
  { id: "1-♠05", deck: 1, suit: "♠", rank: 5, name: "万箭齐发", type: "锦囊" },
  { id: "1-♠06", deck: 1, suit: "♠", rank: 6, name: "普通杀", type: "基本" },
  { id: "1-♠07", deck: 1, suit: "♠", rank: 7, name: "决斗", type: "锦囊" },
  { id: "1-♠08", deck: 1, suit: "♠", rank: 8, name: "普通杀", type: "基本" },
  { id: "1-♠09", deck: 1, suit: "♠", rank: 9, name: "桃", type: "基本" },
  { id: "1-♠10", deck: 1, suit: "♠", rank: 10, name: "诸葛连弩", type: "武器" },
  { id: "1-♠11", deck: 1, suit: "♠", rank: 11, name: "闪", type: "基本" },
  { id: "1-♠12", deck: 1, suit: "♠", rank: 12, name: "无懈可击", type: "锦囊" },
  { id: "1-♠13", deck: 1, suit: "♠", rank: 13, name: "普通杀", type: "基本" },
  { id: "1-♥01", deck: 1, suit: "♥", rank: 1, name: "无中生有", type: "锦囊" },
  { id: "1-♥02", deck: 1, suit: "♥", rank: 2, name: "普通杀", type: "基本" },
  { id: "1-♥03", deck: 1, suit: "♥", rank: 3, name: "桃", type: "基本" },
  { id: "1-♥04", deck: 1, suit: "♥", rank: 4, name: "八卦阵", type: "防具" },
  { id: "1-♥05", deck: 1, suit: "♥", rank: 5, name: "闪", type: "基本" },
  { id: "1-♥06", deck: 1, suit: "♥", rank: 6, name: "无懈可击", type: "锦囊" },
  { id: "1-♥07", deck: 1, suit: "♥", rank: 7, name: "普通杀", type: "基本" },
  { id: "1-♥08", deck: 1, suit: "♥", rank: 8, name: "顺手牵羊", type: "锦囊" },
  { id: "1-♥09", deck: 1, suit: "♥", rank: 9, name: "普通杀", type: "基本" },
  { id: "1-♥10", deck: 1, suit: "♥", rank: 10, name: "桃", type: "基本" },
  { id: "1-♥11", deck: 1, suit: "♥", rank: 11, name: "藤甲", type: "防具" },
  { id: "1-♥12", deck: 1, suit: "♥", rank: 12, name: "闪", type: "基本" },
  { id: "1-♥13", deck: 1, suit: "♥", rank: 13, name: "铁索连环", type: "锦囊" },
  { id: "1-♣01", deck: 1, suit: "♣", rank: 1, name: "火杀", type: "基本" },
  { id: "1-♣02", deck: 1, suit: "♣", rank: 2, name: "过河拆桥", type: "锦囊" },
  { id: "1-♣03", deck: 1, suit: "♣", rank: 3, name: "普通杀", type: "基本" },
  { id: "1-♣04", deck: 1, suit: "♣", rank: 4, name: "酒", type: "基本" },
  { id: "1-♣05", deck: 1, suit: "♣", rank: 5, name: "防御坐骑", type: "坐骑" },
  { id: "1-♣06", deck: 1, suit: "♣", rank: 6, name: "闪", type: "基本" },
  { id: "1-♣07", deck: 1, suit: "♣", rank: 7, name: "寒冰剑", type: "武器" },
  { id: "1-♣08", deck: 1, suit: "♣", rank: 8, name: "雷杀", type: "基本" },
  { id: "1-♣09", deck: 1, suit: "♣", rank: 9, name: "南蛮入侵", type: "锦囊" },
  { id: "1-♣10", deck: 1, suit: "♣", rank: 10, name: "普通杀", type: "基本" },
  { id: "1-♣11", deck: 1, suit: "♣", rank: 11, name: "决斗", type: "锦囊" },
  { id: "1-♣12", deck: 1, suit: "♣", rank: 12, name: "普通杀", type: "基本" },
  { id: "1-♣13", deck: 1, suit: "♣", rank: 13, name: "闪", type: "基本" },
  { id: "1-♦01", deck: 1, suit: "♦", rank: 1, name: "方天画戟", type: "武器" },
  { id: "1-♦02", deck: 1, suit: "♦", rank: 2, name: "闪", type: "基本" },
  { id: "1-♦03", deck: 1, suit: "♦", rank: 3, name: "万箭齐发", type: "锦囊" },
  { id: "1-♦04", deck: 1, suit: "♦", rank: 4, name: "普通杀", type: "基本" },
  { id: "1-♦05", deck: 1, suit: "♦", rank: 5, name: "无中生有", type: "锦囊" },
  { id: "1-♦06", deck: 1, suit: "♦", rank: 6, name: "普通杀", type: "基本" },
  { id: "1-♦07", deck: 1, suit: "♦", rank: 7, name: "桃", type: "基本" },
  { id: "1-♦08", deck: 1, suit: "♦", rank: 8, name: "长刀", type: "武器" },
  { id: "1-♦09", deck: 1, suit: "♦", rank: 9, name: "闪", type: "基本" },
  { id: "1-♦10", deck: 1, suit: "♦", rank: 10, name: "无懈可击", type: "锦囊" },
  { id: "1-♦11", deck: 1, suit: "♦", rank: 11, name: "普通杀", type: "基本" },
  { id: "1-♦12", deck: 1, suit: "♦", rank: 12, name: "无中生有", type: "锦囊" },
  { id: "1-♦13", deck: 1, suit: "♦", rank: 13, name: "普通杀", type: "基本" },
  { id: "2-♠01", deck: 2, suit: "♠", rank: 1, name: "桃", type: "基本" },
  { id: "2-♠02", deck: 2, suit: "♠", rank: 2, name: "八卦阵", type: "防具" },
  { id: "2-♠03", deck: 2, suit: "♠", rank: 3, name: "闪", type: "基本" },
  { id: "2-♠04", deck: 2, suit: "♠", rank: 4, name: "铁索连环", type: "锦囊" },
  { id: "2-♠05", deck: 2, suit: "♠", rank: 5, name: "火杀", type: "基本" },
  { id: "2-♠06", deck: 2, suit: "♠", rank: 6, name: "顺手牵羊", type: "锦囊" },
  { id: "2-♠07", deck: 2, suit: "♠", rank: 7, name: "普通杀", type: "基本" },
  { id: "2-♠08", deck: 2, suit: "♠", rank: 8, name: "桃", type: "基本" },
  { id: "2-♠09", deck: 2, suit: "♠", rank: 9, name: "进攻坐骑", type: "坐骑" },
  { id: "2-♠10", deck: 2, suit: "♠", rank: 10, name: "闪", type: "基本" },
  { id: "2-♠11", deck: 2, suit: "♠", rank: 11, name: "乐不思蜀", type: "延时锦囊" },
  { id: "2-♠12", deck: 2, suit: "♠", rank: 12, name: "火杀", type: "基本" },
  { id: "2-♠13", deck: 2, suit: "♠", rank: 13, name: "过河拆桥", type: "锦囊" },
  { id: "2-♥01", deck: 2, suit: "♥", rank: 1, name: "普通杀", type: "基本" },
  { id: "2-♥02", deck: 2, suit: "♥", rank: 2, name: "酒", type: "基本" },
  { id: "2-♥03", deck: 2, suit: "♥", rank: 3, name: "防御坐骑", type: "坐骑" },
  { id: "2-♥04", deck: 2, suit: "♥", rank: 4, name: "闪", type: "基本" },
  { id: "2-♥05", deck: 2, suit: "♥", rank: 5, name: "寒冰剑", type: "武器" },
  { id: "2-♥06", deck: 2, suit: "♥", rank: 6, name: "雷杀", type: "基本" },
  { id: "2-♥07", deck: 2, suit: "♥", rank: 7, name: "南蛮入侵", type: "锦囊" },
  { id: "2-♥08", deck: 2, suit: "♥", rank: 8, name: "普通杀", type: "基本" },
  { id: "2-♥09", deck: 2, suit: "♥", rank: 9, name: "决斗", type: "锦囊" },
  { id: "2-♥10", deck: 2, suit: "♥", rank: 10, name: "普通杀", type: "基本" },
  { id: "2-♥11", deck: 2, suit: "♥", rank: 11, name: "闪", type: "基本" },
  { id: "2-♥12", deck: 2, suit: "♥", rank: 12, name: "诸葛连弩", type: "武器" },
  { id: "2-♥13", deck: 2, suit: "♥", rank: 13, name: "闪", type: "基本" },
  { id: "2-♣01", deck: 2, suit: "♣", rank: 1, name: "无懈可击", type: "锦囊" },
  { id: "2-♣02", deck: 2, suit: "♣", rank: 2, name: "普通杀", type: "基本" },
  { id: "2-♣03", deck: 2, suit: "♣", rank: 3, name: "无中生有", type: "锦囊" },
  { id: "2-♣04", deck: 2, suit: "♣", rank: 4, name: "普通杀", type: "基本" },
  { id: "2-♣05", deck: 2, suit: "♣", rank: 5, name: "桃", type: "基本" },
  { id: "2-♣06", deck: 2, suit: "♣", rank: 6, name: "长刀", type: "武器" },
  { id: "2-♣07", deck: 2, suit: "♣", rank: 7, name: "闪", type: "基本" },
  { id: "2-♣08", deck: 2, suit: "♣", rank: 8, name: "无懈可击", type: "锦囊" },
  { id: "2-♣09", deck: 2, suit: "♣", rank: 9, name: "普通杀", type: "基本" },
  { id: "2-♣10", deck: 2, suit: "♣", rank: 10, name: "顺手牵羊", type: "锦囊" },
  { id: "2-♣11", deck: 2, suit: "♣", rank: 11, name: "普通杀", type: "基本" },
  { id: "2-♣12", deck: 2, suit: "♣", rank: 12, name: "桃", type: "基本" },
  { id: "2-♣13", deck: 2, suit: "♣", rank: 13, name: "藤甲", type: "防具" },
  { id: "2-♦01", deck: 2, suit: "♦", rank: 1, name: "闪", type: "基本" },
  { id: "2-♦02", deck: 2, suit: "♦", rank: 2, name: "铁索连环", type: "锦囊" },
  { id: "2-♦03", deck: 2, suit: "♦", rank: 3, name: "火杀", type: "基本" },
  { id: "2-♦04", deck: 2, suit: "♦", rank: 4, name: "过河拆桥", type: "锦囊" },
  { id: "2-♦05", deck: 2, suit: "♦", rank: 5, name: "普通杀", type: "基本" },
  { id: "2-♦06", deck: 2, suit: "♦", rank: 6, name: "酒", type: "基本" },
  { id: "2-♦07", deck: 2, suit: "♦", rank: 7, name: "进攻坐骑", type: "坐骑" },
  { id: "2-♦08", deck: 2, suit: "♦", rank: 8, name: "闪", type: "基本" },
  { id: "2-♦09", deck: 2, suit: "♦", rank: 9, name: "乐不思蜀", type: "延时锦囊" },
  { id: "2-♦10", deck: 2, suit: "♦", rank: 10, name: "雷杀", type: "基本" },
  { id: "2-♦11", deck: 2, suit: "♦", rank: 11, name: "过河拆桥", type: "锦囊" },
  { id: "2-♦12", deck: 2, suit: "♦", rank: 12, name: "普通杀", type: "基本" },
  { id: "2-♦13", deck: 2, suit: "♦", rank: 13, name: "酒", type: "基本" },
];

/** 牌名 -> 张数，用于守恒校验。 */
export const BASE_DECK_COUNTS: Record<string, number> = {
  "普通杀": 24,
  "闪": 16,
  "方天画戟": 2,
  "雷杀": 4,
  "万箭齐发": 2,
  "决斗": 3,
  "桃": 8,
  "诸葛连弩": 2,
  "无懈可击": 5,
  "无中生有": 4,
  "八卦阵": 2,
  "顺手牵羊": 3,
  "藤甲": 2,
  "铁索连环": 3,
  "火杀": 4,
  "过河拆桥": 4,
  "酒": 4,
  "防御坐骑": 2,
  "寒冰剑": 2,
  "南蛮入侵": 2,
  "长刀": 2,
  "进攻坐骑": 2,
  "乐不思蜀": 2
};
